# ----------------------- ECHO CONFIGURATION
PORT: "3001"

# ----------------------- ALPHAVANTAGE (3rd Party)
ALPHAVANTAGE_URL: "https://www.alphavantage.co/"
ALPHAVANTAGE_KEY: "91F6TIXC02FNDES8"

# ----------------------- ENCRYPTION SERVICE (3rd Party)
ENCRYPTION_SVC_URL: "http://ftier-encrypt-01:3002/aes/encrypt"