version: "3.7"
services: 
    web:
        container_name: ftier-stock-01
        image: newbee123/ftier-stock
        ports: 
            - "3001:3001"
        depends_on: 
            - app
        volumes: 
            - app.config.yml
        restart: always
        networks:
            - local

    app:
        container_name: ftier-encrypt-01
        image: newbee123/ftier-encrypt:latest
        ports: 
            - "3002:3002"
        restart: always
        networks:
            - local

networks: 
    local:
        name: local
        # newbee123/ftier-stock